// ACTIONS
export const TOGGLE_SLIDER = "TOGGLE_SLIDER";
export const SET_TOKEN = "SET_TOKEN";
export const SET_UNAME = "SET_UNAME";
export const SET_MENU_LIST = "SET_MENU_LIST";
export const CLEAR_TOKEN_CNAME_MENU = "CLEAR_TOKEN_CNAME_MENU";
export const ADD_TODOLIST = "ADD_TODOLIST";
export const REMOVE_TODOLIST = "REMOVE_TODOLIST";
export const DONE_TODOLIST = "DONE_TODOLIST";
export const CLEAR_FILTERTODOS = "CLEAR_FILTERTODOS";

// GETTERS